DM-13618: Find node-hour usage from usage codes
lsst-dm/ldf_ops_tools pull request #4
Opened 2018-02-23 20:14 UTC by Samantha-Thrush

I've added a calculation for node-hours in the usageploy.py code in order easily see how many resources are spent on a given set of slurm jobs.   In order to include this calculation, I've added in a function to calculate node-hours, and have split the previous plotting function definition into two function definition: one for extracting data from the data_file into numpy arrays, and one for creating the plot.

2018-02-23 22:13 UTC, mxk62 requested changes
Firstly, you're making a cardinal sin (;D) mixing spaces and tabs in Python code. Please, configure editor you are using to expand each tabs into spaces (each tab into 4).

Secondly, I cannot see any consistency with regard to the length of the lines in your docstrings. Some of sentences/paragraphs span to the "legal" limit (79 characters) as they should, others seems to be broken half way through. Please, fix it.

Finally, and I apologize for not catching it earlier, the standard types in docstrting (e.g. `str`, `float`) should be enclosed in ` (backticks), not in ' (single quotes), see [this]( https://developer.lsst.io/docs/py_docs.html#describing-parameter-types) part of the official DM Dev Guide.

2018-02-23 22:13 UTC, mxk62 commented on usage/usageplot.py
All functions (and classes) must be separated by *two* blank lines from each other and any other parts of the module (e.g. imports).

2018-02-23 22:13 UTC, mxk62 commented on usage/usageplot.py
Class/function/module summary should preferably be a short, one-line sentence. So either you're forgot to put a blank line between the first and the second line or it is not a good summary. ;)

2018-02-23 22:13 UTC, mxk62 commented on usage/usageplot.py
See my earlier remark regarding summary lines in docstrings.

Also there should be *no* space space between opening """ and the first word of the summary. Please fix it in other docstrings too.

2018-02-23 22:13 UTC, mxk62 commented on usage/usageplot.py
> +
Time intervals used in `usage.py` are all equal. This greatly simplifies calculation of the metric you are interested in:
```python
def get_nodehours(times, nodes):
    """...
    """
    dt = times[1] - times[0]
    return np.sum(dt * nodes)
```

2018-02-26 17:19 UTC, Samantha-Thrush commented
Thank you so much for the review, Mikolaj!  I have resolved all of the issues above and so I think it's ready for your final review!

2018-02-26 18:52 UTC, mxk62 approved these changes
You can merge it to master providing you fix issues I listed below:

1. There are still some leftover tabs (lines: 31, 154), remove them.
2. Insert a blank line after line 17.
3. Move `matplotlib.use('Agg')` after the imports (remember about separating two blank lines).
4. Put a space after `__name__` in line 152.

2018-02-26 19:32 UTC, merged